<?php

class m170514_093836_category extends CDbMigration
{
    public function up()
    {
        $this->createTable('category', array(
            'id' => 'pk',
            'h1_ru' => 'varchar(255) not null',
            'h1_ua' => 'varchar(255) not null',
            'name_ru' => 'varchar(255) not null',
            'name_ua' => 'varchar(255) not null',
            'parent_id' => 'integer(11) default 0',
            'url' => 'varchar(255) not null',
            'order' => 'int(11) default 0',
            'status' => 'tinyint(1) default 1',
            'seo_title_ru' => 'varchar(255) not null',
            'seo_title_ua' => 'varchar(255) not null',
            'seo_description_ru' => 'text not null',
            'seo_description_ua' => 'text not null',
            'seo_keywords_ru' => 'text not null',
            'seo_keywords_ua' => 'text not null',
        ));

        $this->insertMultiple('category', array(
            array(
                'h1_ru' => 'Традиционные котлы',
                'h1_ua' => 'Традиційні котли',
                'name_ru' => 'Традиционные котлы',
                'name_ua' => 'Традиційні котли',
                'parent_id' => 0,
                'url' => '1-traditsionnyye_kotly',
                'order' => 0,
                'seo_title_ru' => 'Традиционные котлы',
                'seo_title_ua' => 'Традиційні котли',
                'seo_description_ru' => 'Традиционные котлы',
                'seo_description_ua' => 'Традиційні котли',
                'seo_keywords_ru' => 'Традиционные котлы',
                'seo_keywords_ua' => 'Традиційні котли',
            ),
            array(
                'h1_ru' => 'С плитой',
                'h1_ua' => 'З плитою',
                'name_ru' => 'С плитой',
                'name_ua' => 'З плитою',
                'parent_id' => 1,
                'url' => '2-s_plitoy',
                'order' => 1,
                'seo_title_ru' => 'С плитой',
                'seo_title_ua' => 'З плитою',
                'seo_description_ru' => 'С плитой',
                'seo_description_ua' => 'З плитою',
                'seo_keywords_ru' => 'С плитой',
                'seo_keywords_ua' => 'З плитою',
            ),
            array(
                'h1_ru' => 'Котел 1 с глубокой топкой 130 КВТ',
                'h1_ua' => 'Котел 1 з глибокою топкою 130 КВТ',
                'name_ru' => 'Котел 1 с глубокой топкой 130 КВТ',
                'name_ua' => 'Котел 1 з глибокою топкою 130 КВТ',
                'parent_id' => 2,
                'url' => '3-kotel_1_s_glubokoy_topkoy_130_kvt',
                'order' => 2,
                'seo_title_ru' => 'Котел 1 с глубокой топкой 130 КВТ',
                'seo_title_ua' => 'Котел 1 з глибокою топкою 130 КВТ',
                'seo_description_ru' => 'Котел 1 с глубокой топкой 130 КВТ',
                'seo_description_ua' => 'Котел 1 з глибокою топкою 130 КВТ',
                'seo_keywords_ru' => 'Котел 1 с глубокой топкой 130 КВТ',
                'seo_keywords_ua' => 'Котел 1 з глибокою топкою 130 КВТ',
            ),
            array(
                'h1_ru' => 'Котел 2 с глубокой топкой 130 КВТ',
                'h1_ua' => 'Котел 2 з глибокою топкою 130 КВТ',
                'name_ru' => 'Котел 2 с глубокой топкой 130 КВТ',
                'name_ua' => 'Котел 2 з глибокою топкою 130 КВТ',
                'parent_id' => 2,
                'url' => '4-kotel_2_s_glubokoy_topkoy_130_kvt',
                'order' => 3,
                'seo_title_ru' => 'Котел 2 с глубокой топкой 130 КВТ',
                'seo_title_ua' => 'Котел 2 з глибокою топкою 130 КВТ',
                'seo_description_ru' => 'Котел 2 с глубокой топкой 130 КВТ',
                'seo_description_ua' => 'Котел 2 з глибокою топкою 130 КВТ',
                'seo_keywords_ru' => 'Котел 2 с глубокой топкой 130 КВТ',
                'seo_keywords_ua' => 'Котел 2 з глибокою топкою 130 КВТ',
            ),
            array(
                'h1_ru' => 'Котел 3 с глубокой топкой 130 КВТ',
                'h1_ua' => 'Котел 3 з глибокою топкою 130 КВТ',
                'name_ru' => 'Котел 3 с глубокой топкой 130 КВТ',
                'name_ua' => 'Котел 3 з глибокою топкою 130 КВТ',
                'parent_id' => 2,
                'url' => '5-kotel_3_s_glubokoy_topkoy_130_kvt',
                'order' => 4,
                'seo_title_ru' => 'Котел 3 с глубокой топкой 130 КВТ',
                'seo_title_ua' => 'Котел 3 з глибокою топкою 130 КВТ',
                'seo_description_ru' => 'Котел 3 с глубокой топкой 130 КВТ',
                'seo_description_ua' => 'Котел 3 з глибокою топкою 130 КВТ',
                'seo_keywords_ru' => 'Котел 3 с глубокой топкой 130 КВТ',
                'seo_keywords_ua' => 'Котел 3 з глибокою топкою 130 КВТ',
            ),
            array(
                'h1_ru' => 'Без плиты',
                'h1_ua' => 'Без плити',
                'name_ru' => 'Без плиты',
                'name_ua' => 'Без плити',
                'parent_id' => 1,
                'url' => '6-bez_plity',
                'order' => 5,
                'seo_title_ru' => 'Без плиты',
                'seo_title_ua' => 'Без плити',
                'seo_description_ru' => 'Без плиты',
                'seo_description_ua' => 'Без плити',
                'seo_keywords_ru' => 'Без плиты',
                'seo_keywords_ua' => 'Без плити',
            ),
            array(
                'h1_ru' => 'Котел 1 с глубокой топкой 130 КВТ',
                'h1_ua' => 'Котел 1 з глибокою топкою 130 КВТ',
                'name_ru' => 'Котел 1 с глубокой топкой 130 КВТ',
                'name_ua' => 'Котел 1 з глибокою топкою 130 КВТ',
                'parent_id' => 6,
                'url' => '7-kotel_1_s_glubokoy_topkoy_130_kvt',
                'order' => 6,
                'seo_title_ru' => 'Котел 1 с глубокой топкой 130 КВТ',
                'seo_title_ua' => 'Котел 1 з глибокою топкою 130 КВТ',
                'seo_description_ru' => 'Котел 1 с глубокой топкой 130 КВТ',
                'seo_description_ua' => 'Котел 1 з глибокою топкою 130 КВТ',
                'seo_keywords_ru' => 'Котел 1 с глубокой топкой 130 КВТ',
                'seo_keywords_ua' => 'Котел 1 з глибокою топкою 130 КВТ',
            ),
            array(
                'h1_ru' => 'Котел 2 с глубокой топкой 130 КВТ',
                'h1_ua' => 'Котел 2 з глибокою топкою 130 КВТ',
                'name_ru' => 'Котел 2 с глубокой топкой 130 КВТ',
                'name_ua' => 'Котел 2 з глибокою топкою 130 КВТ',
                'parent_id' => 6,
                'url' => '8-kotel_2_s_glubokoy_topkoy_130_kvt',
                'order' => 7,
                'seo_title_ru' => 'Котел 2 с глубокой топкой 130 КВТ',
                'seo_title_ua' => 'Котел 2 з глибокою топкою 130 КВТ',
                'seo_description_ru' => 'Котел 2 с глубокой топкой 130 КВТ',
                'seo_description_ua' => 'Котел 2 з глибокою топкою 130 КВТ',
                'seo_keywords_ru' => 'Котел 2 с глубокой топкой 130 КВТ',
                'seo_keywords_ua' => 'Котел 2 з глибокою топкою 130 КВТ',
            ),
            array(
                'h1_ru' => 'Котел 3 с глубокой топкой 130 КВТ',
                'h1_ua' => 'Котел 3 з глибокою топкою 130 КВТ',
                'name_ru' => 'Котел 3 с глубокой топкой 130 КВТ',
                'name_ua' => 'Котел 3 з глибокою топкою 130 КВТ',
                'parent_id' => 6,
                'url' => '9-kotel_3_s_glubokoy_topkoy_130_kvt',
                'order' => 8,
                'seo_title_ru' => 'Котел 3 с глубокой топкой 130 КВТ',
                'seo_title_ua' => 'Котел 3 з глибокою топкою 130 КВТ',
                'seo_description_ru' => 'Котел 3 с глубокой топкой 130 КВТ',
                'seo_description_ua' => 'Котел 3 з глибокою топкою 130 КВТ',
                'seo_keywords_ru' => 'Котел 3 с глубокой топкой 130 КВТ',
                'seo_keywords_ua' => 'Котел 3 з глибокою топкою 130 КВТ',
            ),
            array(
                'h1_ru' => 'С глубокой топкой',
                'h1_ua' => 'З глибокою топкою',
                'name_ru' => 'С глубокой топкой',
                'name_ua' => 'З глибокою топкою',
                'parent_id' => 1,
                'url' => '10-s_glubokoy_topkoy',
                'order' => 9,
                'seo_title_ru' => 'С глубокой топкой',
                'seo_title_ua' => 'З глибокою топко',
                'seo_description_ru' => 'С глубокой топкой',
                'seo_description_ua' => 'З глибокою топко',
                'seo_keywords_ru' => 'С глубокой топкой',
                'seo_keywords_ua' => 'З глибокою топко',
            ),
            array(
                'h1_ru' => 'Котел 1 с глубокой топкой 130 КВТ',
                'h1_ua' => 'Котел 1 з глибокою топкою 130 КВТ',
                'name_ru' => 'Котел 1 с глубокой топкой 130 КВТ',
                'name_ua' => 'Котел 1 з глибокою топкою 130 КВТ',
                'parent_id' => 10,
                'url' => '11-kotel_1_s_glubokoy_topkoy_130_kvt',
                'order' => 10,
                'seo_title_ru' => 'Котел 1 с глубокой топкой 130 КВТ',
                'seo_title_ua' => 'Котел 1 з глибокою топкою 130 КВТ',
                'seo_description_ru' => 'Котел 1 с глубокой топкой 130 КВТ',
                'seo_description_ua' => 'Котел 1 з глибокою топкою 130 КВТ',
                'seo_keywords_ru' => 'Котел 1 с глубокой топкой 130 КВТ',
                'seo_keywords_ua' => 'Котел 1 з глибокою топкою 130 КВТ',
            ),
            array(
                'h1_ru' => 'Котел 2 с глубокой топкой 130 КВТ',
                'h1_ua' => 'Котел 2 з глибокою топкою 130 КВТ',
                'name_ru' => 'Котел 2 с глубокой топкой 130 КВТ',
                'name_ua' => 'Котел 2 з глибокою топкою 130 КВТ',
                'parent_id' => 10,
                'url' => '12-kotel_2_s_glubokoy_topkoy_130_kvt',
                'order' => 11,
                'seo_title_ru' => 'Котел 2 с глубокой топкой 130 КВТ',
                'seo_title_ua' => 'Котел 2 з глибокою топкою 130 КВТ',
                'seo_description_ru' => 'Котел 2 с глубокой топкой 130 КВТ',
                'seo_description_ua' => 'Котел 2 з глибокою топкою 130 КВТ',
                'seo_keywords_ru' => 'Котел 2 с глубокой топкой 130 КВТ',
                'seo_keywords_ua' => 'Котел 2 з глибокою топкою 130 КВТ',
            ),
            array(
                'h1_ru' => 'Котел 3 с глубокой топкой 130 КВТ',
                'h1_ua' => 'Котел 3 з глибокою топкою 130 КВТ',
                'name_ru' => 'Котел 3 с глубокой топкой 130 КВТ',
                'name_ua' => 'Котел 3 з глибокою топкою 130 КВТ',
                'parent_id' => 10,
                'url' => '13-kotel_3_s_glubokoy_topkoy_130_kvt',
                'order' => 12,
                'seo_title_ru' => 'Котел 3 с глубокой топкой 130 КВТ',
                'seo_title_ua' => 'Котел 3 з глибокою топкою 130 КВТ',
                'seo_description_ru' => 'Котел 3 с глубокой топкой 130 КВТ',
                'seo_description_ua' => 'Котел 3 з глибокою топкою 130 КВТ',
                'seo_keywords_ru' => 'Котел 3 с глубокой топкой 130 КВТ',
                'seo_keywords_ua' => 'Котел 3 з глибокою топкою 130 КВТ',
            ),
            array(
                'h1_ru' => 'Котлы длительного горения',
                'h1_ua' => 'Котли тривалого горіння',
                'name_ru' => 'Котлы длительного горения',
                'name_ua' => 'Котли тривалого горіння',
                'parent_id' => 0,
                'url' => '14-kotly_dlitelnogo_goreniya',
                'order' => 13,
                'seo_title_ru' => 'Котлы длительного горения',
                'seo_title_ua' => 'Котли тривалого горіння',
                'seo_description_ru' => 'Котлы длительного горения',
                'seo_description_ua' => 'Котли тривалого горіння',
                'seo_keywords_ru' => 'Котлы длительного горения',
                'seo_keywords_ua' => 'Котли тривалого горіння',
            ),
            array(
                'h1_ru' => 'Пеллетные котлы',
                'h1_ua' => 'Пелетні котли',
                'name_ru' => 'Пеллетные котлы',
                'name_ua' => 'Пелетні котли',
                'parent_id' => 0,
                'url' => '15-pelletnyye_kotly',
                'order' => 14,
                'seo_title_ru' => 'Пеллетные котлы',
                'seo_title_ua' => 'Пелетні котли',
                'seo_description_ru' => 'Пеллетные котлы',
                'seo_description_ua' => 'Пелетні котли',
                'seo_keywords_ru' => 'Пеллетные котлы',
                'seo_keywords_ua' => 'Пелетні котли',
            ),
            array(
                'h1_ru' => 'Котлы большой мощности',
                'h1_ua' => 'Котли великої потужності',
                'name_ru' => 'Котлы большой мощности',
                'name_ua' => 'Котли великої потужності',
                'parent_id' => 0,
                'url' => '16-kotly_bolshoy_moshchnosti',
                'order' => 15,
                'seo_title_ru' => 'Котлы большой мощности',
                'seo_title_ua' => 'Котли великої потужності',
                'seo_description_ru' => 'Котлы большой мощности',
                'seo_description_ua' => 'Котли великої потужності',
                'seo_keywords_ru' => 'Котлы большой мощности',
                'seo_keywords_ua' => 'Котли великої потужності',
            ),
            array(
                'h1_ru' => 'Модульные котельные',
                'h1_ua' => 'Модульні котельні',
                'name_ru' => 'Модульные котельные',
                'name_ua' => 'Модульні котельні',
                'parent_id' => 0,
                'url' => '17-modulnyye_kotelnyye',
                'order' => 16,
                'seo_title_ru' => 'Модульные котельные',
                'seo_title_ua' => 'Модульні котельні',
                'seo_description_ru' => 'Модульные котельные',
                'seo_description_ua' => 'Модульні котельні',
                'seo_keywords_ru' => 'Модульные котельные',
                'seo_keywords_ua' => 'Модульні котельні',
            ),
            array(
                'h1_ru' => 'Баки Теплоаккумуляторы',
                'h1_ua' => 'Баки Теплоаккумулятори',
                'name_ru' => 'Баки Теплоаккумуляторы',
                'name_ua' => 'Баки Теплоаккумулятори',
                'parent_id' => 0,
                'url' => '18-baki_teploakkumulyatory',
                'order' => 17,
                'seo_title_ru' => 'Баки Теплоаккумуляторы',
                'seo_title_ua' => 'Баки Теплоаккумулятори',
                'seo_description_ru' => 'Баки Теплоаккумуляторы',
                'seo_description_ua' => 'Баки Теплоаккумулятори',
                'seo_keywords_ru' => 'Баки Теплоаккумуляторы',
                'seo_keywords_ua' => 'Баки Теплоаккумулятори',
            ),
            array(
                'h1_ru' => 'Дымоходы',
                'h1_ua' => 'Димарі',
                'name_ru' => 'Дымоходы',
                'name_ua' => 'Димарі',
                'parent_id' => 0,
                'url' => '19-dymokhody',
                'order' => 18,
                'seo_title_ru' => 'Дымоходы',
                'seo_title_ua' => 'Димарі',
                'seo_description_ru' => 'Дымоходы',
                'seo_description_ua' => 'Димарі',
                'seo_keywords_ru' => 'Дымоходы',
                'seo_keywords_ua' => 'Димарі',
            ),
            array(
                'h1_ru' => 'Запчасти и доп. материалы',
                'h1_ua' => 'Запчастини і доп. матеріали',
                'name_ru' => 'Запчасти и доп. материалы',
                'name_ua' => 'Запчастини і доп. матеріали',
                'parent_id' => 0,
                'url' => '20-zapchasti',
                'order' => 19,
                'seo_title_ru' => 'Запчасти и доп. материалы',
                'seo_title_ua' => 'Запчастини і доп. матеріали',
                'seo_description_ru' => 'Запчасти и доп. материалы',
                'seo_description_ua' => 'Запчастини і доп. матеріали',
                'seo_keywords_ru' => 'Запчасти и доп. материалы',
                'seo_keywords_ua' => 'Запчастини і доп. матеріали',
            ),
        ));
    }

    public function down()
    {
        $this->dropTable('category');
    }
}