<?php

return array(
    'defaultController' => 'index',
    'language' => 'ru',
    'sourceLanguage' => 'ru',
    'timeZone' => 'UTC',
    'import' => array(
        'application.models.*',
        'application.components.*',
    ),
    'components' => array(
        'urlManager' => array(
            'class' => 'application.components.UrlManager',
            'urlFormat' => 'path',
            'showScriptName' => false,
            'rules' => array(
                '<language:(ru|uk)>' => 'index/index',
                '' => 'index/index',
                '<language:(ru|uk)>/about' => 'about/index',
                'about' => 'about/index',
                '<language:(ru|uk)>/advantage' => 'advantage/index',
                'advantage' => 'advantage/index',
                'category/more/<id>' => 'category/more',
                'category/more' => 'category/more',
                'category/check/<id>' => 'category/check',
                'category/check' => 'category/check',
                '<language:(ru|uk)>/category/<id>' => 'category/view',
                'category/<id>' => 'category/view',
                '<language:(ru|uk)>/category' => 'category/index',
                'category' => 'category/index',
                '<language:(ru|uk)>/consult' => 'consult/index',
                'consult' => 'consult/index',
                '<language:(ru|uk)>/contact' => 'contact/index',
                'contact' => 'contact/index',
                '<language:(ru|uk)>/credit' => 'credit/index',
                'credit' => 'credit/index',
                '<language:(ru|uk)>/dealer' => 'dealer/index',
                'dealer' => 'dealer/index',
                '<language:(ru|uk)>/guarantee' => 'guarantee/index',
                'guarantee' => 'guarantee/index',
                '<language:(ru|uk)>/news' => 'news/index',
                'news' => 'news/index',
                'news/more' => 'news/more',
                'news/check' => 'news/check',
                '<language:(ru|uk)>/payment' => 'payment/index',
                'payment' => 'payment/index',
                'product/image/<id>' => 'product/image',
                'product/more/<id>' => 'product/more',
                'product/more' => 'product/more',
                'product/check/<id>' => 'product/check',
                'product/check' => 'product/check',
                '<language:(ru|uk)>/product/<id>/<category_id>' => 'product/view',
                '<language:(ru|uk)>/product/<id>' => 'product/view',
                'product/<id>' => 'product/view',
                '<language:(ru|uk)>/product' => 'product/index',
                'product' => 'product/index',
                'project/more/<id>' => 'project/more',
                'project/more' => 'project/more',
                'project/check/<id>' => 'project/check',
                'project/check' => 'project/check',
                '<language:(ru|uk)>/project/<id>' => 'project/index',
                'project/<id>' => 'project/index',
                '<language:(ru|uk)>/project' => 'project/index',
                'project' => 'project/index',
                '<language:(ru|uk)>/review' => 'review/index',
                'review' => 'review/index',
                'review/more' => 'review/more',
                'review/check' => 'review/check',
                '<language:(ru|uk)>/video' => 'video/index',
                'video' => 'video/index',
                'video/more/<id>' => 'video/more',
                'video/check/<id>' => 'video/check',
                'why' => 'why/index',
                '<language:(ru|uk)>/why' => 'why/index',
                '<language:(ru|uk)>/<controller>/<action>/<id>' => '<controller>/<action>',
                '<language:(ru|uk)>/<controller>/<action>' => '<controller>/<action>',
                '<language:(ru|uk)>/<controller>' => '<controller>/index',
                '<module:(admin)>/<language:(ru|uk)>/<controller>/<action>/<id>' => '<module>/<controller>/<action>',
                '<module:(admin)>/<language:(ru|uk)>/<controller>/<action>' => '<module>/<controller>/<action>',
                '<module:(admin)>/<language:(ru|uk)>/<controller>' => '<module>/<controller>',
                '<module:(admin)>/<language:(ru|uk)>' => '<module>/index',
                '<module:(admin)>/<controller>/<action>/<id>' => '<module>/<controller>/<action>',
                '<module:(admin)>/<controller>/<action>' => '<module>/<controller>/<action>',
                '<module:(admin)>/<controller>' => '<module>/<controller>',
                '<module:(admin)>' => '<module>/index',
            ),
        ),
        'db' => array(
            'connectionString' => 'mysql:host=localhost;dbname=igosja_marten',
            'emulatePrepare' => true,
            'username' => 'igosja_marten',
            'password' => '&WKWp@*{',
            'charset' => 'utf8',
        ),
        'messages' => array(
            'class' => 'CDbMessageSource',
            'cacheID' => 'cache',
            'cachingDuration' => 43200,
            'connectionID' => 'db',
            'sourceMessageTable' => 'i18n_source_messages',
            'translatedMessageTable' => 'i18n_translated_messages',
            'forceTranslation' => true,
        ),
    ),
    'modules' => array(
        'admin',
        'gii' => array(
            'class' => 'system.gii.GiiModule',
            'password' => '123',
        ),
    ),
);